<?php
$navbar = $element['navbar'];
$footer = $element['footer'];
?>
<?php
echo $navbar;
?>
<h1>Booking Completed</h1>
<p>Thanks for using Dean Training, see you soon on the training.</p>

<div class="col-md-6 col-md-offset-3 text-center image-center">
    <img src="/v2/img/thanks.jpg" class="img-responsive">
    <br>
    <a href="<?= $this->Helper->generateRoute('index', 'index', 'index'); ?>" class="btn btn-success btn-lg"><i class="fa fa-arrow-circle-o-left"></i> Go Back</a>
    <br/><br/>
</div>

<?php
echo $footer;
