<?php
$navbar = $element['navbar'];
$footer = $element['footer'];
$titlebar = $element['titlebar'];
?>
<?php
echo $navbar;
echo $titlebar;
?>
    <div class="col-md-12">
        <p>PLEASE READ THE TERMS &amp; CONDITIONS CAREFULLY BEFORE BOOKING A COURSE WITH US ONLINE, AT ONE OF OUR
            CENTRES OR OVER THE PHONE. IT IS EXPECTED THAT YOU HAVE READ THE T&amp;C'S BEFORE MAKING YOUR BOOKING.</p>
        <p>&nbsp;</p>
        <p>1.1 All Dean Training Limited prices are subject to change until the customer has made the payment.</p>
        <p>&nbsp;</p>
        <p>1.2 100% attendance is a must; any late arrivals are not acceptable.</p>
        <p>&nbsp;</p>
        <p>1.3 Please Note: Any sort of unacceptable behaviour at all Dean Training Limited venues will lead to
            exclusion from the course for which we will not offer any refund.</p>
        <p>&nbsp;</p>
        <p>1.4 All bookings are subject to availability of spaces and relevant resources.</p>
        <p>&nbsp;</p>
        <p>1.5 Customers who make the booking via phone, email or through our website are liable for any balance
            outstanding (if any), in full.</p>
        <p>&nbsp;</p>
        <p>1.6 Candidates must be eligible to attend the training course you book with us. Please check that you meet
            all criteria before reserving a space on any of the Dean Training Limited courses.</p>
        <p>&nbsp;</p>
        <p>1.7 Reservations/bookings made online, at one of our centres or over the phone are non-refundable.</p>
        <p>&nbsp;</p>
        <p>1.8 Reservations made online can be transferred to any individual who is eligible to attend.</p>
        <p>&nbsp;</p>
        <p>1.9 Dean Training Limited reserves the right to change the venue of training with another suitable venue. We
            will notify all candidates via email, text or telephone at least 24 hours before the start of the course.
            Please note we may only ever change the venue location if there is an utmost need for it and there is no
            other option available to us to accommodate customers at the original location.</p>
        <p>&nbsp;</p>
        <p>2.0 In the unlikely event of cancellation of any courses by Dean Training Limited, damages shall be limited
            to a full refund of the course fee only. In the event of cancellation due to the lockdown during the pandemic or
        any government guidance where centre wouldn't be open refund will be not be applicable - alternative date will be offered
        at no extra charge.</p>
        <p>&nbsp;</p>
        <p>2.1 All certificates are recorded delivered via royal mail, at a cost of &pound;10. Collections can be made by
            customers with prior notification only at £5 cost.</p>
        <p>&nbsp;</p>
        <p>2.2 Customers will be responsible to pay any awarding body charges for replacement certificates. Dean
            Training Limited accepts no liability for misplaced certificates. The replacement certificate fee is &pound;20.
            Customers can choose from the following two options for Certification delivery: 1. collection from our
            head office. 2.recorded delivery via a royal mail at the cost of &pound;10. Dean Training Limited will not be
            liable to pay for any damages, including replacement certificate charges, for any claims of lost/misplaced
            certificates for this service. We do not process any claims of lost/misplaced certificates after 30 calendar
            days from the date of dispatch of certification to clients for this service.</p>
        <p>&nbsp;</p>
        <p>2.3 For all Identity Validation forms used by our awarding bodies, the candidate is to only sign such
            validation form if the spelling of their name on such a form is absolutely correct. Please note that failure
            to do so will result in the candidate being liable for any administration costs charged by the awarding body
            for correction.</p>
        <p>&nbsp;</p>
        <p>2.4 All customers are responsible and must provide Dean Training Limited with correct and accurate
            information (using clear handwriting) in respect to the physical address, requested by the admin, where all
            certificates will be dispatched.</p>
        <p>&nbsp;</p>
    </div>

<?php
echo $footer;

