<?php
$navbar = $element['navbar'];
$footer = $element['footer'];
$titlebar = $element['titlebar'];
?>
<?php
echo $navbar;
echo $titlebar;
?>
    <div class="col-md-12">
        <p><h4>Purchases made from REED.co.uk:</h4></p>
        <p>&nbsp;</p>
        <p>- Under this policy, you may cancel your purchase of the course within the period of 14 calendar days from the date on which the contract of purchase is concluded. This is called a "Cancellation Period". Note that if you redeem your voucher during the Cancellation Period, you expressly request us to begin providing the course materials and you acknowledge that you lose your right to cancel the purchase of the course and get any refund for it.</p>
        <p>&nbsp;</p>
        <p>- In case you decide to cancel your purchase of a course, it can be done in the following way:</p>
        <p>&nbsp;</p>
        <p>- By filling out Cancellation Form and sending it via (PROVIDER PLEASE INSERT POSTAL OR EMAIL ADDRESS)</p>
        <p>&nbsp;</p>
        <p>- If you cancel the purchase of a course within 14 calendar days as mentioned above, we will refund you for all payments made as a part of your purchase within 14 calendar days from the day we accept that you are entitled to a refund.</p>
        <br/><br/>
    </div>

<?php
echo $footer;

