<?php
$navbar = $element['navbar'];
$footer = $element['footer'];
$titlebar = $element['titlebar'];
?>
<?php
echo $navbar;
echo $titlebar;
?>
<div class="col-md-8 col-md-offset-2">
    <div class='row'>
        <div class='col-md-3 text-center'><i class='fa fa-random fa-5x color-primary'></i><h3 class='color-primary'>Dynamic</h3><p class='text-left collapse'>The constant influx of new clients , new ideas and a positive approach to assess the challenges is a big part of the reason why we have been the most dynamic training centre in London and Beyond.</p><p><a class="btn btn-default btn-view-more" href="#">View details &raquo;</a></p></div>
        <div class='col-md-3 text-center'><i class='fa fa-balance-scale fa-5x color-primary'></i><h3  class='color-primary'>Ethical</h3><p class='text-left collapse'>We cannot make you feel something you do not feel,but we can support you to make you to do right decision in spite of your feelings based upon tomorrow world.</p><p><a class="btn btn-default btn-view-more" href="#">View details &raquo;</a></p></div>
        <div class='col-md-3 text-center'><i class='fa fa-check-square-o fa-5x color-primary'></i><h3  class='color-primary'>Accredited</h3><p class='text-left collapse'>Clearly, evidence of candidates learning gains under properly accredited instructor will be the first step toward reaching the goal of producing quality instructor.We’ve been part of this exciting initiative since the beginning and we are pleased to be able to enable more respected organisation to join the circle.</p><p><a class="btn btn-default btn-view-more" href="#">View details &raquo;</a></p></div>
        <div class='col-md-3 text-center'><i class='fa fa-users fa-5x color-primary'></i><h3  class='color-primary'>Nexus</h3><p class='text-left collapse'>We promote that knowledge wins exams, but teamwork and intelligence wins championships.</p><p><a class="btn btn-default btn-view-more" href="#">View details &raquo;</a></p></div>
    </div>

    <div class="panel-group" id="accordion1">
        <div class="panel panel-default panel-collapse">
            <div class="panel-heading">
                <h5 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_1">When</a>
                </h5>
            </div>
            <div id="accordion1_1" class="panel-collapse collapse in">
                <div class="panel-body">
                    <p>Dean training was formed in 2010 committed to invest in the community to create a safer environment for both candidates, employers and general public with the aid of like minded partners via vocational training related to all sectors of the security industry. Due to transferable skills further selected industries have been embraced and over the years Dean Training has proven to be a reliable organisation with the scope to address the needs of small, medium and large organisations without sacrificing the DEAN standard.</p>                   
                </div>
            </div>
        </div>
        <div class="panel panel-default panel-collapse">
            <div class="panel-heading">
                <h5 class="panel-title">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_2">Where</a>
                </h5>
            </div>
            <div id="accordion1_2" class="panel-collapse collapse">
                <div class="panel-body">
                    <p>Dean Training is originally a London based organisation and is dynamically expanding our centres, not to be the largest, but simply the best! to Bristol, Birmingham and Manchester. We have a background in the industry sectors that we instruct in as services provider. We believe it is imperative for our centres having easy access to persons with and without their transport and address the needs of the disabled. Our centres have all resources related to the sector training, enhancing the chances of addressing the visual, auditory and kinetic learning domains.Please note that we are able to deliver “in-house” courses on an international scale.</p>
                </div>
            </div>
        </div>
        <div class="panel panel-default panel-collapse">
            <div class="panel-heading">
                <h5 class="panel-title">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_3">Who</a>
                </h5>
            </div>
            <div id="accordion1_3" class="panel-collapse collapse">
                <div class="panel-body">
                    <p>Dean training comprises of a collation of refined industry sector specialists with a proven track record of a minimum of a decade (front-line), we are all experienced in delivering commercial, private and bespoke courses to an array of candidate profiles, motivated to make a positive change in tomorrow’s world, all instructors have been affiliated with one another since the 1990′s and consciously wish to invest leaving a legacy of. Professional ethics ,first hand knowledge and first hand experience that will assure your growth as a refined professional operative in the security industry.</p>
                </div>
            </div>
        </div>
        <div class="panel panel-default panel-collapse">
            <div class="panel-heading">
                <h5 class="panel-title">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_4">What</a>
                </h5>
            </div>
            <div id="accordion1_4" class="panel-collapse collapse">
                <div class="panel-body">
                    <p>We initially specialised in the provision of security services in the 1990′s.  The Private Security Act 2001, was introduced in Hampshire and eventually was introduced in London in 2004, which was the catalyst for us to embrace the training sector. We worked for several organisations and found that the foundation and motivation of those organisations was based on financial gain solely. We as instructors have a passion and commitment to over and above the industry standard.We take pride in our level of training and resources we invest in our candidates, therefore in 2010 we launched the Dynamic Ethical Accredited Nexus(DEAN) destined to make a positive contribution to tomorrows world via vocational training by the best instructors in the United Kingdom.</p>
                </div>
            </div>
        </div>
        <div class="panel panel-default panel-collapse">
            <div class="panel-heading">
                <h5 class="panel-title">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_5">Why</a>
                </h5>
            </div>
            <div id="accordion1_5" class="panel-collapse collapse">
                <div class="panel-body">
                    <ul class="list-course">
                        <li>Dean Training is registered with ICO for Data Protection Act with the (ref no)</li>
                        <li>We record all communication for quality assurance purposes, whether it be an email or phone call.</li>
                        <li>The DEAN team conduct assessments whether it be an individual wishing to become a close protection operative or an organisation wishing to up skill their team of security operatives, as a result ensuring all your requirements are met.</li>
                        <li>You will be tracked whether being an individual wishing to training to gain employment or an organisation wishing to attain trained competent operatives.</li>
                        <li>Your career growth in right satisfying way is our goal, therefore you will never see work as work again but a means to gain freedom, we will achieve this by communication and mutual understanding. Guiding you and making you realise your professional potential in right way.</li>
                        <li>We are all trained in diversity and equality and much more relative wisdom.</li>
                        <li>We will tool you with the knowledge and application to guarantee employment.</li>
                        <li>Ongoing support in career or your business interest.</li>
                        <li>We use today’s technology in any way it can benefit end user and all other parties involved.</li>
                        <li>We under promise and over deliver.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="panel panel-default panel-collapse">
            <div class="panel-heading">
                <h5 class="panel-title">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_6">How</a>
                </h5>
            </div>
            <div id="accordion1_6" class="panel-collapse collapse">
                <div class="panel-body">
                    <p>
                        There was a need for an organisation that practiced what it preached,
                    </p>
                    <p><strong>Dynamic;</strong> an expression of action than a state of being, we don’t believe there are any benefits in procrastination, we continuously seek to identify strengths, weaknesses, opportunities and threats, in tomorrow’s world, therefore the courses we deliver will guarantee sustainable income not just for tomorrow and not  just in the UK and apply various avenues of communication in a systematic, pro-active manner.</p>
                    <p><strong>Ethical;</strong> Adhering to standards and moral principles, we make sure that the rules and standards set by accredited bodies like SIA,Highfeild are practiced by DEAN TRAINING I.e teaching hours and examination regulations. we believe in values we don’t breach our morals&principles and continue to thrive to put our students interest forward with quality assurance by the awarding bodies.</p>
                    <p><strong>Accredited;</strong> official approval, all of our tutors are screened and accredited as are our courses by internationally recognised Awarding Bodies.we believe in achieving high standards and are working towards ISO 9000.</p>
                    <p><strong>Nexus;</strong> connected group, Dean training is unique as to we open our doors to all persons and organisations with integrity and values as we do and wish to be a part of organisations alike, we appreciate there are dishonest persons and organisations in this sector, just like any other and ensure we blow the whistle in order to alert the likes of Awarding bodies and relative agencies but this does not stop us from maintaining positive growth.</p>
                </div>
            </div>
        </div>

        <div class="panel panel-default panel-collapse">
            <div class="panel-heading">
                <h5 class="panel-title">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_7">Corporate and Social Responsibilities</a>
                </h5>
            </div>
            <div id="accordion1_7" class="panel-collapse collapse">
                <div class="panel-body">
                    <p>As a business we are committed to promoting economic growth; tackling poverty and social exclusion in the communities where we work and to minimising our environmental impact.</p>
                    <ul class="list-course">
                        <li>We are working towards the Environmental Management ISO 14001 Award.</li>
                        <li>Reducing our carbon footprint</li>
                        <li>Email, telephone and audio conferencing is encouraged where possible</li>
                        <li>Recycling is mandatory at all of our sites (where appropriate / DPA)</li>
                        <li>Lighting and electrical equipment is turned off when not in use</li>
                        <li>NVQ portfolios are electronic (where possible) to reduce waste</li>
                        <li>Emails are not printed unless absolutely necessary</li>
                        <li>Apprenticeship Assessors are home based and work with employers in their region, minimising travel</li>
                        <li>Promoting carbon reduction</li>
                        <li>We encourage our partners, clients and learners to reduce waste, minimise their environmental impact and improve efficiency in use of resources</li>
                    </ul>
                    <strong>Charity Support</strong>
                    <p>
                        Our corporate responsibility includes, donating 2% of our profits to worthy causes.Contributions will be made to 7 legitimate registered charities/benevolent funds.
                    </p>
                    <ul class="list-course">
                        <li>UNICEF</li>
                        <li>World vision</li>
                        <li>Muslim aid</li>
                        <li>Baps charities</li>
                        <li>Third world orphans</li>
                        <li>Further suggestions are welcome</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="panel panel-default panel-collapse">
            <div class="panel-heading">
                <h5 class="panel-title">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#accordion1_8">Accreditations</a>
                </h5>
            </div>
            <div id="accordion1_8" class="panel-collapse collapse">
                <div class="panel-body">
                    <p>
                        <strong>Companies house</strong><br/>
                        Registration Number: 7369031
                    </p>

                    <p>
                        <strong>HRM</strong><br/>
                        Vat registration: 139 4210 25
                    </p>

                    <p>
                        <strong>Insurance</strong><br/>
                        Registration Number: HU PI6 1696306
                    </p>

                    <p>
                        <strong>Data protection</strong><br/>
                        Registration Number: Z239076X
                    </p>

                    <p>
                        <strong>UKRLP</strong><br/>
                        Registration Number: 10031114
                    </p>

                    <p>
                        <strong>Job Centre (DUNSNS)</strong><br/>
                        Registration Number :216893199
                    </p>

                    <p>
                        <strong>HighfieldABC</strong><br/>
                        Registration Number :11018
                    </p>

                    <p>
                        <strong>Institute of learning</strong><br/>
                        Registration Number :AD010368
                    </p>
                    <p>
                        <strong>ELCAS - Enhanced Learning Credits Administration Services</strong><br/>
                        Accreditation Number :5778
                    </p>
                    <strong>Others:</strong>
                    <ul class="list-course">
                        <li>Professional indemnity insurance</li>
                        <li>Public and products liability insurance</li>
                        <li>EMPLOYERS’ LIABILITY INSURANCE</li>
                        <li>Procserve</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


    <div class='row'>
        <div class='col-md-4'><div class='text-center color-primary'><i class='fa fa-4x fa-life-saver'></i></div><h3 class='color-primary text-center'>Responsibility</h3><p class="collapse"> We act ethically and with responsibility in all we do for the benefit of our clients, our candidates and the wider community. We donate 2% of turnover to charity. We are a carbon neutral business.</p><p class="text-center"><a class="btn btn-default btn-view-more" href="#">View details &raquo;</a></p></div>
        <div class='col-md-4'><div class='text-center color-primary'><i class='fa fa-4x fa-star-half-full'></i></div><h3 class='color-primary text-center'>Service</h3><p class="collapse">We understand that our next candidate is our next potential client and we aim to bring an excellent consultative and caring service to the professionals that we work for.</p><p class="text-center"><a class="btn btn-default btn-view-more" href="#">View details &raquo;</a></p></div>
        <div class='col-md-4'><div class='text-center color-primary'><i class='fa fa-4x fa-trophy'></i></div><h3 class='color-primary text-center'>Pride</h3><p class="collapse">We care about what we do and we do it to our utmost abilities to help the people that we serve.</p><p class="text-center"><a class="btn btn-default btn-view-more" href="#">View details &raquo;</a></p></div>
        <div class='clearfix'></div>
        <div class='col-md-4'><div class='text-center color-primary'><i class='fa fa-4x fa-umbrella'></i></div><h3 class='color-primary text-center'>100% Guaranteed</h3><p class="collapse"> All our courses are covered by the DEAN Guarantee. Therefore you can book with total confidence knowing that, our prices are competitive and we do not postpone or cancel courses. This is applicable to all of our customers.</p><p class="text-center"><a class="btn btn-default btn-view-more" href="#">View details &raquo;</a></p></div>
        <div class='col-md-4'><div class='text-center color-primary'><i class='fa fa-4x fa-users'></i></div><h3 class='color-primary text-center'>Community</h3><p class="collapse"> We are at the centre of the fastest growing industry and are affiliated with leading thought leadership groups that bring people together through networking events and industry leading content. We build lasting relationships with the best specialist professionals in the world.</p><p class="text-center"><a class="btn btn-default btn-view-more" href="#">View details &raquo;</a></p></div>
        <div class='col-md-4'><div class='text-center color-primary'><i class='fa fa-4x fa-book'></i></div><h3 class='color-primary text-center'>Knowledge</h3><p class="collapse"> We are the best in class due to our deep specialisation and understanding the industry sectors that we work in. </p><p class="text-center"><a class="btn btn-default btn-view-more" href="#">View details &raquo;</a></p></div>
        <div class='clearfix'></div>
        <div class='col-md-4 col-md-offset-4'><div class='text-center color-primary'><i class='fa fa-4x fa-clock-o'></i></div><h3 class='color-primary text-center'>Delivery</h3><p class="collapse"> We deliver the best service and the best results to the people that we serve in a bespoke time frame. </p><p class="text-center"><a class="btn btn-default btn-view-more" href="#">View details &raquo;</a></p></div>        
    </div>
</div>
<?php
echo $footer;
