<?php
$navbar = $element['navbar'];
$footer = $element['footer'];
$titlebar = $element['titlebar'];
?>
<?php
echo $navbar;
echo $titlebar;
?>
    <br/>
    <div class="col-md-6 col-md-offset-3 text-left image-center">


        <div class="panel panel-default">
            <div class="panel-heading"><i class='fa fa-money'></i> Value for money</div>
            <div class="panel-body">
                <p>In-house training is a cost effective option for groups of staff, teams facing specific challenges or
                    senior management needing to focus. By running a course in-house you will also save money on staff
                    travel and hotel expenses.</p>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><i class='fa fa-calendar-o'></i> Flexible Group Training</div>
            <div class="panel-body">
                <p>
                    If you have a group of six or more to train in a particular subject you can save time and money by
                    running an in-house course.
                </p>
                <p>
                    An in-house course can be delivered at your offices, your choice of venue or one of our training
                    venues anywhere in the world. We regularly deliver training all over the world through our in-house
                    courses option.
                </p>
                <p>
                    If you have less than six staff to train, you may wish to look at our public workshops (Central
                    London).
                </p>
                <p>
                    Our complete range of courses can be delivered as an in-house option. We can also tailor an existing
                    course (to a relevant business challenge or to mirror your organisation’s standards) or design a new
                    programme to meet your objectives.
                </p>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><i class='fa fa-clock-o'></i> Your time and venue</div>
            <div class="panel-body">
                <p>You choose a time and venue and we will try to meet your requirements. If you need help in finding
                    the right venue we can offer this as a part of the in-house service.</p>
                <p>If you are based overseas, or need the course delivered overseas we will try and meet your
                    requirements.</p>
                <p>Running an in-house course means you can focus on the issues relevant to your team, improve
                    motivation and help with team building.</p>
                <p>As well as running one-off courses to address specific needs, we specialise in working with our
                    clients to put together high impact programmes of courses and that address a range of development
                    requirements.</p>
                <p>With wide experience of running tailored programmes for both large and small organisations, we would
                    love to talk to you about your needs.</p>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><i class='fa fa-money'></i> Pricing</div>
            <div class="panel-body">
                <table class='table table-bordered'>
                    <tr>
                        <th>Qualification</th>
                        <th>Days</th>
                        <th>Open Course Price (Per Person)</th>
                        <th>In House Price</th>
                    </tr>
                    <tr>
                        <td>Level 2 Emergency First Aid</td>
                        <td>1/2</td>
                        <td>49</td>
                        <td>299</td>
                    </tr>


                    <tr>
                        <td>Level 3 First Aid At Work</td>
                        <td>3</td>
                        <td>149</td>
                        <td>999</td>
                    </tr>
                    <tr>
                        <td>Level 2 Defibrillation</td>
                        <td>1/2</td>
                        <td>75</td>
                        <td>299</td>
                    </tr>
                    <tr>
                        <td>Level 1 Fire Safety / Marshal</td>
                        <td>1</td>
                        <td>49</td>
                        <td>299</td>
                    </tr>
                    <tr>
                        <td>Level 2 Fire Safety / Marshal</td>
                        <td>1</td>
                        <td>99</td>
                        <td>399</td>
                    </tr>
                    <tr>
                        <td>Level 1 Health and Safety for Construction</td>
                        <td>1</td>
                        <td>125</td>
                        <td>399</td>
                    </tr>
                    <tr>
                        <td>Level 2 Handcuffing</td>
                        <td>1</td>
                        <td>149</td>
                        <td>499</td>
                    </tr>
                    <tr>
                        <td>Counter Terrorism Awareness</td>
                        <td>1</td>
                        <td>150</td>
                        <td>349</td>
                    </tr>
                    <tr>
                        <td>Traffic Marshall</td>
                        <td>1/2</td>
                        <td>49</td>
                        <td>299</td>
                    </tr>
                    <tr>
                        <td>Level 2 Door Supervision</td>
                        <td>4</td>
                        <td>149</td>
                        <td>999</td>
                    </tr>
                    <tr>
                        <td>Level 2 UpSkilling Door Supervision</td>
                        <td>1.5</td>
                        <td>99</td>
                        <td>499</td>
                    </tr>
                    <tr>
                        <td>Level 2 CCTV Operations</td>
                        <td>3-4</td>
                        <td>199</td>
                        <td>999</td>
                    </tr>
                    <tr>
                        <td>Level 3 Close Protection</td>
                        <td>13</td>
                        <td>999</td>
                        <td>4999</td>
                    </tr>
                    <tr>
                        <td>Screening &amp; Vetting BS7858</td>
                        <td>1</td>
                        <td>199</td>
                        <td>499</td>
                    </tr>
                </table>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><i class='fa fa-phone'></i> Want to Find Out More?</div>
            <div class="panel-body">
                <p>We would love to discuss your requirements with us. Please contact our friendly and experienced team
                    or phone +44 (0) 2089657818.</p>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><i class='fa fa-credit-card'></i> Book Now</div>
            <div class="panel-body">
                <p>Please fill out this contact form and one of our representative will come back to you shortly. </p>
                <form id='contactForm' method="post"
                      action="<?= $this->Helper->generateRoute('book', 'Groupbooking', 'request') ?>">
                    <h5><span class="text-danger">*</span> Required</h5>

                    <div class="form-group">
                        <label for="name">Full Name <span class="text-danger">*</span></label>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-pencil"></i></span>
                            <input type="text" class="form-control" id="name" name="name" data-validation="length"
                                   data-validation-length="3-255"/>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="email">Email Address <span class="text-danger">*</span></label>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-mobile"></i></span>
                            <input type="text" class="form-control" id="email" name="email" data-validation="email"/>
                        </div>
                    </div>


                    <div class="form-group">
                        <label for="number">Mobile Number <span class="text-danger">*</span></label>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-pencil"></i></span>
                            <input type="text" class="form-control" id="number" name="number" data-validation="length"
                                   data-validation-length="3-255"/>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="message">Message <span class="text-danger">*</span></label>
                        <textarea name="message" id="message" class="form-control" rows="5"></textarea>
                    </div>

                    <div class="text-center">
                        <button type="submit" class="btn btn-success btn-lg" data-loading-text="Loading..."/>
                        Submit</button>
                    </div>

                    <br/>

                </form>
            </div>
        </div>

    </div>

<?php
echo $footer;
