<?php
$navbar = $element['navbar'];
$footer = $element['footer'];
$course_drop = $element['course'];
?>
<?php
echo $navbar;
?>



<div class="row">
    <div class="col-md-8">

        <h1>Certificate Request</h1>
        <p>Request of certificate via postage cost £5.</p>
        
        <br/>
        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">

            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="8ZEK9UH9Y242E">

            <div class="form-group">
                <label for="os0"><input type="hidden" name="on0" value="Full Name">Full Name <span class="text-danger">*</span></label>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-pencil"></i></span>
                    <input type="text" class="form-control" id="os0" name="os0" data-validation="length" data-validation-length="3-255"/>                       
                </div>
            </div>

            <div class="form-group">
                <label for="os1"><input type="hidden" name="on1" value="Course">Please Select The Course <span class="text-danger">*</span></label>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-book"></i></span>
                    <select name="os1" id="os1" class="form-control selectpicker" data-live-search='true' data-validation="required">
                        <option value="">Select Course</option>
                        <?= $course_drop; ?>
                    </select>
                </div>
            </div>

            <br/>           
            
            <center><input type="submit" class='btn btn-success btn-lg'  border="0" name="submit" value="Pay now"> </center>
            <img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
        </form>

        <br/>        <br/>        <br/>
    </div>

    <div class="col-md-4">     
        <br/><br/>
        <center>              
            <img src="/v2/img/secure-payment.png" width="200"/><br/>
            <img src="/v2/img/paypal.jpg" width="200"/><br/>
        </center>
    </div>
</div>


<?php
echo $footer;
