<link rel="stylesheet" type="text/css" href="%BASEURL%/css/reset.css" />
<link rel="stylesheet" type="text/css" href="%BASEURL%/external/jqueryui/jqueryui.css" />
<link rel="stylesheet" type="text/css" href="%BASEURL%/external/jqueryui/jquery-ui-theme.css" />
<link rel="stylesheet" type="text/css" href="%BASEURL%/external/fonticon/style/fonticon.css" />
<link rel="stylesheet" href="%BASEURL%/external/bootstrap/style/bootstrap.css" />
<link rel="stylesheet" href="%BASEURL%/external/bootstrap/style/bootstrap-theme.css" />
<link rel="stylesheet" href="%BASEURL%/external/lightbox/fancybox.css" />
<link rel="stylesheet" href="%BASEURL%/external/bounce/style.css" />
<link rel="stylesheet" type="text/css" href="%BASEURL%/css/style.css" />
