<link rel="stylesheet" type="text/css" href="/css/reset.css" />
<link rel="stylesheet" type="text/css" href="/external/jqueryui/jqueryui.css" />
<link rel="stylesheet" type="text/css" href="/external/jqueryui/jquery-ui-theme.css" />
<link rel="stylesheet" type="text/css" href="/external/fonticon/style/fonticon.css" />
<link rel="stylesheet" href="/external/bootstrap/style/bootstrap.css" />
<link rel="stylesheet" href="/external/bootstrap/style/bootstrap-theme.css" />
<link rel="stylesheet" href="/external/lightbox/fancybox.css" />
<link rel="stylesheet" href="/external/bounce/style.css" />

<link rel="stylesheet" type="text/css" href="/css/style.css" />