<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
    %cssfiles%
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="IE=10">
    <title>%title%</title>
    <meta name="keywords" content="%keywords%"/>
    <meta name="description" content="%description%"/>
    <link rel="shortcut icon" href="%BASEURL%/img/favicon.png" type="image/x-icon"/>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-7225635583129586",
            enable_page_level_ads: true
        });
    </script>
    <!--  Clickcease.com tracking-->
    <script type="text/javascript">
        var script = document.createElement("script");
        script.async = true;
        script.type = "text/javascript";
        var target = 'https://www.clickcease.com/monitor/stat.js';
        script.src = target;
        var elem = document.head;
        elem.appendChild(script);
    </script>
    <noscript><a href="https://www.clickcease.com" rel="nofollow"><img
                    src="https://monitor.clickcease.com/stats/stats.aspx" alt="ClickCease"/></a></noscript>
    <!--  Clickcease.com tracking-->
</head>
<div class="container-fluid">
    %sessionflags%