<?php
$navbar = $element['navbar'];
$footer = $element['footer'];
$titlebar = $element['titlebar'];
?>
<?php
echo $navbar;
echo $titlebar;
?>
<div class="col-md-12">
    <h3>DEAN TRAINING LIMITED WILL NOT ISSUE A REFUND UNDER THE FOLLOWING CIRCUMSTANCES AS PER OUR T&C'S</h3>

    <ul>
        <li>• If the learner does not attend the course that they have booked for.</li>
        <li>• If the learner is late in starting the training</li>
        <li>• If a deposit has already been made to secure a place on a course.</li>
        <li>• If the learner provides insufficient ID.</li>
        <li>• If the learner rearranges the course and cannot attend on the dates they have arranged for.</li>
        <li>• If student is self isolating during the pandemic of COVID 19 - alternative date will be offered.</li>
        <li>• If centre would be under lock down due to pandemic or any other government restrictions - alternative date will be offered.</li>
    </ul>
    <br/>
    <h3>DEAN TRAINING LIMITED WILL ISSUE A REFUND UNDER THE FOLLOWING CIRCUMSTANCES AS PER OUR T&C'S</h3>
    <ul>
        <li>• If a course is cancelled from our end. (Under no circumstances will the company issue a refund with the payment exceeding the original amount paid to us. Dean Training Limited is not responsible, nor will we compensate for any accommodation or transport costs, or loss of earnings due to time taken off work.)</li>
        <li>• If a learner has taken a level 2 course or below and hasn’t received results within 3 months without valid reasoning from the company.</li>
        <li>• If a learner has taken a level 3 course and hasn’t received results within 6 months without valid reasoning from the company.</li>
        <li>• If a learner has taken a level 4 course and hasn’t received results within 9 months without valid reasoning from the company.</li>
    </ul>
    <p>Our Support Team is always eager to assist you and deliver highly professional support in a timely manner. Thank you for booking a course with Dean Training Limited.</p>
    <br/><br/>
</div>
<?php
echo $footer;
